# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ea10534b4b9a9fc7e581c9df52c571d23d2695ba9a28ce038d715bf97e88114002d83145ac6c4813fba66eb8a7b91c3fd94a96faf921859da4f91fa677a43a

test:
  secret_key_base: 61c98404149a0164650fc5075bbd3c77107452cfda5473a9122956fafff97b0e5312813a9a39b9ae23a7a0127c8e1ab97db47e4c974a6b95ea33ac05a03ce60c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
